[project]
name = "singlecellexperiment"
dynamic = [
    "version",
]
description = "Container class for single-cell experiments"
readme = "README.md"
authors = [
    { name = "Jayaram Kancherla", email = "jayaram.kancherla@gmail.com" },
]
requires-python = ">=3.9"
keywords = [
    "bioinformatics",
    "single-cell",
    "RNA-seq",
    "transcriptomics",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Typing :: Typed",
]
dependencies = [
    "compressed-lists>=0.4.3",
    "summarizedexperiment>=0.6.3",
]


[project.license]
file = "LICENSE.txt"


[project.urls]
Homepage = "https://github.com/BiocPy/singlecellexperiment"
Documentation = "https://biocpy.github.io/singlecellexperiment/"
Source = "https://github.com/BiocPy/singlecellexperiment"
"Bug Tracker" = "https://github.com/BiocPy/singlecellexperiment/issues"

[project.optional-dependencies]
optional = [
    "anndata==0.9.2 ; python_full_version < '3.10'",
    "anndata>0.9.2 ; python_full_version >= '3.10'",
    "delayedarray",
    "h5py",
    "hdf5array",
    "mudata==0.2.3 ; python_full_version < '3.10'",
    "mudata>0.2.3 ; python_full_version >= '3.10'",
    "numpy==1.24.4 ; python_full_version < '3.10'",
    "numpy>1.24.4 ; python_full_version >= '3.10'",
]
testing = [
    "anndata==0.9.2 ; python_full_version < '3.10'",
    "anndata>0.9.2 ; python_full_version >= '3.10'",
    "delayedarray",
    "h5py",
    "hdf5array",
    "mudata==0.2.3 ; python_full_version < '3.10'",
    "mudata>0.2.3 ; python_full_version >= '3.10'",
    "numpy==1.24.4 ; python_full_version < '3.10'",
    "numpy>1.24.4 ; python_full_version >= '3.10'",
    "pytest",
    "pytest-cov",
]

[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.1.0"

[tool.ruff]
line-length = 120
src = [
    "src",
]
exclude = [
    "tests",
    "docs",
]

[tool.ruff.lint]
extend-ignore = [
    "F821",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "E402",
    "F401",
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing"
testpaths = [
    "tests",
]

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B110"]
